/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface SpiAdd {
    'home': RouterHistory;
  }
  interface SpiAddAttributes extends StencilHTMLAttributes {
    'home'?: RouterHistory;
  }

  interface SpiDetails {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface SpiDetailsAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface SpiEnseignant {}
  interface SpiEnseignantAttributes extends StencilHTMLAttributes {}

  interface SpiHeader {}
  interface SpiHeaderAttributes extends StencilHTMLAttributes {}

  interface SpiHome {}
  interface SpiHomeAttributes extends StencilHTMLAttributes {}

  interface SpiRoot {}
  interface SpiRootAttributes extends StencilHTMLAttributes {}

  interface SpiSearch {}
  interface SpiSearchAttributes extends StencilHTMLAttributes {}

  interface SpiSearchbyname {}
  interface SpiSearchbynameAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'SpiAdd': Components.SpiAdd;
    'SpiDetails': Components.SpiDetails;
    'SpiEnseignant': Components.SpiEnseignant;
    'SpiHeader': Components.SpiHeader;
    'SpiHome': Components.SpiHome;
    'SpiRoot': Components.SpiRoot;
    'SpiSearch': Components.SpiSearch;
    'SpiSearchbyname': Components.SpiSearchbyname;
  }

  interface StencilIntrinsicElements {
    'spi-add': Components.SpiAddAttributes;
    'spi-details': Components.SpiDetailsAttributes;
    'spi-enseignant': Components.SpiEnseignantAttributes;
    'spi-header': Components.SpiHeaderAttributes;
    'spi-home': Components.SpiHomeAttributes;
    'spi-root': Components.SpiRootAttributes;
    'spi-search': Components.SpiSearchAttributes;
    'spi-searchbyname': Components.SpiSearchbynameAttributes;
  }


  interface HTMLSpiAddElement extends Components.SpiAdd, HTMLStencilElement {}
  var HTMLSpiAddElement: {
    prototype: HTMLSpiAddElement;
    new (): HTMLSpiAddElement;
  };

  interface HTMLSpiDetailsElement extends Components.SpiDetails, HTMLStencilElement {}
  var HTMLSpiDetailsElement: {
    prototype: HTMLSpiDetailsElement;
    new (): HTMLSpiDetailsElement;
  };

  interface HTMLSpiEnseignantElement extends Components.SpiEnseignant, HTMLStencilElement {}
  var HTMLSpiEnseignantElement: {
    prototype: HTMLSpiEnseignantElement;
    new (): HTMLSpiEnseignantElement;
  };

  interface HTMLSpiHeaderElement extends Components.SpiHeader, HTMLStencilElement {}
  var HTMLSpiHeaderElement: {
    prototype: HTMLSpiHeaderElement;
    new (): HTMLSpiHeaderElement;
  };

  interface HTMLSpiHomeElement extends Components.SpiHome, HTMLStencilElement {}
  var HTMLSpiHomeElement: {
    prototype: HTMLSpiHomeElement;
    new (): HTMLSpiHomeElement;
  };

  interface HTMLSpiRootElement extends Components.SpiRoot, HTMLStencilElement {}
  var HTMLSpiRootElement: {
    prototype: HTMLSpiRootElement;
    new (): HTMLSpiRootElement;
  };

  interface HTMLSpiSearchElement extends Components.SpiSearch, HTMLStencilElement {}
  var HTMLSpiSearchElement: {
    prototype: HTMLSpiSearchElement;
    new (): HTMLSpiSearchElement;
  };

  interface HTMLSpiSearchbynameElement extends Components.SpiSearchbyname, HTMLStencilElement {}
  var HTMLSpiSearchbynameElement: {
    prototype: HTMLSpiSearchbynameElement;
    new (): HTMLSpiSearchbynameElement;
  };

  interface HTMLElementTagNameMap {
    'spi-add': HTMLSpiAddElement
    'spi-details': HTMLSpiDetailsElement
    'spi-enseignant': HTMLSpiEnseignantElement
    'spi-header': HTMLSpiHeaderElement
    'spi-home': HTMLSpiHomeElement
    'spi-root': HTMLSpiRootElement
    'spi-search': HTMLSpiSearchElement
    'spi-searchbyname': HTMLSpiSearchbynameElement
  }

  interface ElementTagNameMap {
    'spi-add': HTMLSpiAddElement;
    'spi-details': HTMLSpiDetailsElement;
    'spi-enseignant': HTMLSpiEnseignantElement;
    'spi-header': HTMLSpiHeaderElement;
    'spi-home': HTMLSpiHomeElement;
    'spi-root': HTMLSpiRootElement;
    'spi-search': HTMLSpiSearchElement;
    'spi-searchbyname': HTMLSpiSearchbynameElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
